apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bms-producer
  namespace: bbmp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bms-producer
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80