name: Build and push bbmp portal
on:
  pull_request:
    paths:
      - 'ui/**'
    branches:
      - master
      
  push:
    paths:
      - 'ui/**'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest      
    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/docker-login@v1
      with:
        login-server: index.docker.io
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}   
    
    - run: |
        working-directory: ./ui
        docker build . -t nikeshumredkar/chbms-portal-ui:master-${{ github.sha }
        docker push nikeshumredkar/chbms-portal-ui:master-${{ github.sha }}
        
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'chbms-portal-prod'
        images: 'nikeshumredkar/chbms-portal-ui:master-${{ github.sha }}'    
