# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - chbms-producer-prod(Production), Build and deploy Spring app

on:
  pull_request:
    paths:
      - 'Portal/Backend/bms-producer/**'
      - '!./**'

    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build with Maven
      working-directory: ./Backend/bms-producer
      run: mvn clean install
      
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: java-app
        path: '${{ github.workspace }}/Backend/bms-producer/target/*.jar'  

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: chbms-producer-prod
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FF9BA664018E40B7B2BD592B0A5C78AB }}
        package: ${{ github.workspace }}/target/*.jar

