name: Build and push bbmp portal
on:
  push:
    paths:
      - 'ui/**'
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest      
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD     
    - name: docker build
      working-directory: ./ui
      run: |

        docker build . -t nikeshumredkar/chbms-portal-ui:${{BRANCH_NAME}}-${{ github.sha }}
    - name: docker push
      run: |
        docker push nikeshumredkar/chbms-portal-ui:${BRANCH_NAME}-${{ github.sha }}