name: Build and push bbmp portal
on:   
  push:
    paths:
      - 'ui/**'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest      
    steps:
    - uses: actions/checkout@v2
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 6
    - run: echo $SHA
      env: 
        SHA: ${{ steps.short-sha.outputs.sha }}
    - run: echo $SHA
      env: 
        SHA: ${{ env.SHA }}
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERIO_USERNAME }}
        password: ${{ secrets.DOCKERIO_PASSWORD }} 
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
          context: ./ui
          file: ./ui/Dockerfile
          push: true
          tags: nikeshumredkar/chbms-portal-ui:master-${{ env.SHA }}
     #run: |
     #    docker build -f ui/Dockerfile --build-arg "WORK_DIR=ui" -t index.docker.io/nikeshumredkar/chbms-portal-ui:master-${{ github.sha }} .
     #    docker push index.docker.io/nikeshumredkar/chbms-portal-ui:master-${{ github.sha }}
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:
    - uses: actions/checkout@v2
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 6
    - run: echo $SHA
      env: 
        SHA: ${{ steps.short-sha.outputs.sha }}
    - run: echo $SHA
      env: 
        SHA: ${{ env.SHA }}
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chbms-portal-prod'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1b04ca20f0f8495eb412e7b76f9c36cc }}
        images: 'index.docker.io/${{ secrets.DOCKERIO_USERNAME }}/chbms-portal-ui:master-${{ env.SHA }}' 
      
      
    #- uses: azure/webapps-deploy@v2
    #  with:
    #    app-name: 'chbms-portal-prod'
    #   images: 'nikeshumredkar/chbms-portal-ui:master-${{ github.sha }}'    
