name: Build and push bbmp portal
on:
  pull_request:
    paths:
      - 'ui/**'
    branches:
      - master
      
  push:
    paths:
      - 'ui/**'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest      
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD     
    - name: docker build
      working-directory: ./ui
      run: |
        docker build . -t nikeshumredkar/chbms-portal-ui:master-${{ github.sha }}
    - name: docker push
      run: |
        docker push nikeshumredkar/chbms-portal-ui:master-${{ github.sha }}
        
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'chbms-portal-prod'
        images: 'nikeshumredkar/chbms-portal-ui:master-${{ github.sha }}'    
