# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - chbma-pqs-test(Production), Build and deploy Spring app

on:
  push:
    paths:
      - 'Backend/patient-queue/**'
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build with Maven
      working-directory: ./Backend/patient-queue/
      run: mvn clean package
      
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: java-app
        path: '${{ github.workspace }}/Backend/patient-queue/target/*.jar' 
        
  deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }} 
     
      steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
         name: java-app      

      - name: Run Azure webapp deploy action using publish profile credentials
        uses: azure/webapps-deploy@v2
        with:
          app-name: chbma-pqs-test
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1F291184F80743D6B264957BB1016CB3 }}
          package: '*.jar'

