# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chbms-portal-test

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_49f35206a6ec4823ba2e33bebed8c7b9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ac839b6284c54aab934360992e718498 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_49f35206a6ec4823ba2e33bebed8c7b9 }}/nikeshumredkar/chbms-portal-ui:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chbms-portal-test'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_52ee6a97ba8242c3bee51aee91a6abb3 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_49f35206a6ec4823ba2e33bebed8c7b9 }}/nikeshumredkar/chbms-portal-ui:${{ github.sha }}'