# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - chbms-producer-test(Production), Build and deploy Spring app

on:
  push:
    paths:
      - 'Backend/bms-producer/**'
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build with Maven
      working-directory: ./Backend/bms-producer/
      run: mvn clean package
    
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: java-app
        path: '${{ github.workspace }}/Backend/bms-producer/target/*.jar'
 
  deploy:
     runs-on: ubuntu-latest
     needs: build
     environment:
       name: 'production'
       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

     steps:
     - name: Download artifact from build job
       uses: actions/download-artifact@v2
       with:
         name: java-app

     - name: Run Azure webapp deploy action using publish profile credentials
       uses: azure/webapps-deploy@v2
       with:
        app-name: chbms-producer-test
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8DA018E4233142AB876FB003AFD58A32 }}
        package: '*.jar'

